- name: Open a firewall port
  hosts: all
  tasks:
    - name: Open port
      become: true
      loop: "{{ protocols }}"
      when:
        - port is defined
        - protocols is defined
      ansible.posix.firewalld:
        port: "{{ port }}/{{ item }}"
        state: enabled
        permanent: true
        immediate: true
