- name: Open a service on firewall
  hosts: all
  tasks:
    - name: Open service
      become: true
      when:
        - service_name is defined
      ansible.posix.firewalld:
        service: "{{ service_name }}"
        state: enabled
        permanent: true
        immediate: true
