- name: Manage satellite
  hosts: localhost
  connection: local
  tasks:
    - name: Get content view info
      register: content_view_result
      redhat.satellite.content_view_info:
        server_url: "{{ satellite_config.url }}"
        organization: "{{ satellite_config.organization }}"
        username: "{{ satellite_config.username }}"
        password: "{{ satellite_config.password }}"
        validate_certs: "{{ satellite_config.verify }}"
        name: "{{ content_view }}"

    - name: Get environment id
      ansible.builtin.set_fact:
        environment_id: "{{ (content_view_result.content_view.environments | selectattr('name', 'equalto', selected_environment))[0]['id'] }}"

    - name: Print environment id
      ansible.builtin.debug:
        var: environment_id

    - name: Get current version of environment
      ansible.builtin.set_fact:
        current_version: "{{ (content_view_result.content_view.versions | selectattr('environment_ids', 'contains', environment_id | int))[0]['version'] }}"

    - name: Print content view version of environment
      ansible.builtin.debug:
        msg: "Environment {{ selected_environment }} is {{ current_version }} before rollback"

